---
- name: Test connectivity to hosts
  hosts: all  # Możesz określić konkretną grupę hostów np. "webservers"
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/python3' if 'Python 3' in python_version_check.stdout else '/usr/bin/python' }}"
  tasks:
    - name: Check Python version
      raw: "python --version || python3 --version"
      register: python_version_check
      changed_when: false
      failed_when: false
    - name: Set Python binary based on version check
      set_fact:
         ansible_python_interpreter: "{{ '/usr/bin/python3' if 'Python 3' in python_version_check.stdout else '/usr/bin/python' }}"
    # - name: Ping the hosts to test connectivity
    #   ansible.builtin.ping:
    - name: Create folder
      ansible.builtin.file:
        path: /testowy  # Ścieżka do folderu, który chcesz utworzyć
        state: directory
        mode: '0755'
